modules/game_textmessage/textmessage.otui

Change in the anchor statusLabel so that it is always on top of the console and never behind him.
When you press Ctrl + . you can not view the error messages .
Current version: http://prntscr.com/61k0wb
Correction: http://prntscr.com/61k0l3

Update on textmessage.otui

---

src/framework/CMakeLists.txt

Just like I noted in [this pull request](https://github.com/otland/forgottenserver/pull/1310) on otland/forgottenserver, we should use `-march=native` to turn on aggressive optimizations on best-performance builds. There were some hardcoded defaults in the CMakeLists which I have replaced with the improved flag.

Use native optimizations instead of hardcoded defaults

---

src/framework/util/crypt.cpp

`RSA* RSA_generate_key` is deprecated from OpenSSL [(source)](https://www.openssl.org/docs/crypto/RSA_generate_key_ex.html). I replaced it with the modern version.
Without this change, it does not compile on bleeding edge Linux distros such as Arch Linux.

Replace deprecated function

---

modules/corelib/ui/uiminiwindowcontainer.lua

Mini windows containers was exceeding the size of the panels because they were considering the invisible windows as part of total height.

Fixed issue in function fitAll

---

src/framework/CMakeLists.txt
src/framework/cmake/FindCXX11.cmake

The test performed to check for c++11 is not reliable: it breaks without notice and uses a deprecated flag (most compilers now use `c++11` instead of `c++0x`).
This will make CMake fail prior to compiling with a message. Also it enables to compile with Clang, since it requires `-stdlib=libc++`.

Replace deprecated c++11 test with cmake script

---

src/client/protocolgameparse.cpp

The vocation id was not being received by the client.
https://github.com/otland/forgottenserver/issues/1982

Fix to receive the vocation id from the server protocolgameparse.cpp

---

src/framework/util/matrix.h

This line creates a ton of warnings on a newer version of GCC since the header is included almost everywhere.

Fix misleading indentation

---

src/client/map.cpp

Method Map::addThing uses two times function onAppear for object Missile.
First used in line 119, but then used again the same function in line 165.
Without first function onAppear method Map::addThing work the same.

[Probable bug] Double use function onAppear

---

src/client/game.cpp

Fixed problems with selecting moving monsters in battle list.
Fixed problems with using hotkeys item on creatures (protocol < 780).
Answer to issues:
[#856](https://github.com/edubart/otclient/issues/856)
[#697](https://github.com/edubart/otclient/issues/697)
Threads with this problem on OTLand:
[Problem with Battle - Monsters.](https://otland.net/threads/problem-with-battle-monsters.247449/)
[Can only use this rune on creatures [Bug?]](https://otland.net/threads/can-only-use-this-rune-on-creatures-bug.239093/)

Fixed problem with function "useWith" on creatures

---

modules/game_market/market.lua

This addresses #869. It happens because the market window is always present, just hidden when it's not active, rather than being destroyed and passing the focus back.

Fix game interface not gaining focus after exitting the market

---

modules/client_options/game.otui
modules/client_options/options.lua
modules/game_hotkeys/hotkeys_manager.lua
modules/game_interface/gameinterface.lua

This partially addresses #903 and #564.
I don't think limiting the packet rate is a good solution since the behavior could be desired in many actions and would otherwise make the client feel clunky but since hotkey actions are sent at the rate of foreground FPS this should address the issue where too many actions are being sent by turn and hotkey keys.
The delay can be configured through Options -> Game settings panel.

Add turn and hotkey delay

---

modules/client_options/game.otui
modules/client_options/options.lua
src/client/const.h
src/client/creature.cpp
src/client/luafunctions.cpp
src/client/mapview.cpp
src/client/mapview.h
src/client/uimap.h

This partially addresses #75. It merely adds a mana bar for just the local player though and not all players but it can be easily extended with custom op codes if needed.

Add player mana bar

---

src/client/luafunctions.cpp
src/client/thingtype.cpp
src/client/thingtype.h

Adding function who changing item attribute (ThingAttrNotPathable).
Allows to walk on not pathable items (ThingAttrNotPathable -> true) like parcels, fire fields etc. and vice versa.
Modifying item attribute without editing items sources files. Temporary action for the duration of the client session.
Usage:
```
print(g_things.getThingType(3504):isNotPathable()) -> true
g_things.getThingType(3504):setPathable(true)
print(g_things.getThingType(3504):isNotPathable()) -> false
```
Helpful for highter levels players to ignoring "avoiding" fire/energy/poison fields etc. when using map click.

Add setPathable() function

---

modules/client_topmenu/topmenu.lua
modules/game_interface/gameinterface.lua
modules/game_interface/gameinterface.otui

This PR adds a shortcut (Ctrl-Shift-T) that lets you toggle the top menu visibility to save some vertical space.

Add a keyboard shortcut to toggle topmenu visibility

---

modules/client_background/background.lua

Add compiler name and version to start screen (client_background module).
It would help distinguish OTClient problems on different compilations.

Add compiler info to version label in start screen

---

init.lua

Newer PhysFS version requires a trailing slash for the write directory, otherwise an empty file is created instead.
Older versions should remain unaffected.
This fixes https://github.com/edubart/otclient/issues/468#issuecomment-36684359.

Fix write dir missing a trailing slash

---

modules/corelib/ui/tooltip.lua

This just expands upon the horizontal tooltip behavior where the tooltip is offset so that it stays within the screen bounds. Now it works across both axes.

Fix vertical tooltip clamping

---

modules/gamelib/ui/uiminimap.lua

- Add parameter 'temporary' to method 'UIMinimap:addFlag', who prevents saving flag with this parameter (look 'UIMinimap:save' method), add flag only at game session time. Old parameters list work the same at previous - backward compatibility.
- Add possibility to add icon from outside (for example from module folder) using link to this file. Old system with choose flag name by number work the same at previous, now method check if paramether is number then use old system otherwise get icon from path - backward compatibility. 'Mods' friendly.

Add functionality to minimap flags system

---

modules/corelib/ui/uiminiwindow.lua
modules/corelib/ui/uiminiwindowcontainer.lua

Change type of checking whether window have on drop possibility.
Reason:
Previously this parameter was checking by class name, so it blocking creating similar objects to miniwindow or inheritance from miniwindow object without changing sources. So it block creating modules with new UI objects working with miniwindowcontainer.
Additional feature:
Flag set to false has blocking dropping miniwindow in right/left panel.
So it provide to use miniwindow in other tasks.

UIMiniWindowContainer small improve

---

src/framework/stdext/compiler.h

Change "msvc12" compiler name to "Visual Studio [13-17]" for Visual Studio compiler. 
Name based on "_MSC_VER" parameter.

Change outdated compiler name for VS

---

modules/game_console/console.lua

This suppresses message prefixes on messages without a player name as those are often used for event announcements and result in a weird message format.

Don't apply message prefixes to messages with empty name

---

modules/corelib/ui/uimovabletabbar.lua

The event should be removed when selecting a tab, otherwise when you select a blinking tab and then deselect it, it will remain in the urgent state.

Fix tab blink

---

modules/game_skills/skills.lua

1. Change colors on certain values, when stamina time was change.
2. Change tooltip on certain values, when stamina time was change.
3. Work with most protocols, including the most popular (8.54 - 10.98).
4. In protocols >= 1031 use information about premium account to show if player have premium stamina time.
Fix #989 
Stamina info from: https://github.com/otland/forgottenserver/blob/5438d50b35bc531f35eb188a1e51ccf17af5ebb7/data/events/scripts/player.lua#L254-L259

Show more information in stamina bar

---

src/client/animator.cpp
src/client/animator.h
src/client/effect.cpp
src/client/effect.h

This makes the magic effects use their animation frame duration based on the animation data from the .dat file instead of a static duration like older client versions.

Fix magic effect animations in newer client versions

---

src/framework/platform/win32crashhandler.cpp
src/framework/stdext/demangle.cpp

When building otclient using MSVC with specific Windows SDK versions, it produces warnings related to the imagehlp.h and dbghelp.h SDK headers. Since this is an error on Microsoft's part and there's nothing we can do to fix these in otclient, I figured we might as well silence the warnings for these two headers to filter out this random noise from the build log.

Silence Windows SDK warnings when building with MSVC

---

modules/game_textmessage/textmessage.otui

Fix problem with display text messages in setupViewMode - 2 ([CTRL + .] x 2).
Status messages was display in other place (higher than player character).
Problem:
Fix:

Fix problem with display text in setupViewMode_2

---

vc14/settings.props

Change OTClient version from 0.6.3 to 0.6.6 in Visual Studio project.

Update OTClient outdated version in VS project

---

src/framework/util/crypt.cpp

OpenSSL did some otclient-breaking changes around 1.1.0, 
this patch should work on both < and >= 1.1.0
- **warning**: UNTESTED as of writing. this fixes the compilation errors, but since i only work on tibia 7.6 (which doesn't use encryption, encryption was implemented in tibia 7.7), i haven't actually tested this patch, should probably get someone to test it before pulling it upstream.

OpenSSL >= 1.1.0 compatibility

---

src/framework/luafunctions.cpp
src/framework/net/outputmessage.cpp
src/framework/net/outputmessage.h

This method similar to method setBuffer of InputMessage class will able to easy data copy from one OutputMessage/InputMessage to other.
May be helpful for make cast system using TCP/IP protocol.

Add setBuffer() method to OutputMessage class

---

modules/game_console/console.lua

The OTML nodes are saved in the key: value format where the key is the table index in this case, however reading the values back from OTML turns those number values into string values, rendering #table ineffective. This makes the ignore list and whitelist get properly restored from the config.

Fix saving ignore list and whitelist

---

modules/client_stats/stats.lua

for example spaces should be %20 encoded and the @ in `Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz` should be encoded to %40
but the real problem is the possibility that these stings may include the `&` character, which should be encoded as %25 (but wasn't prior to this commit)

urlencode stuff

---

src/framework/ui/uimanager.cpp
src/framework/ui/uiwidget.cpp

This changes the mouse move event propagation to only send the event to widgets whose rect contains the mouse position. Currently otclient will propagate the event to every single widget on the screen, even those that aren't really interested in the event and it becomes worse the more windows/widgets you have on the screen. In the most pathological case in my client that would be up to 1500~ events per mouse move with the current implementation, down to just about 8~ in the same scenario with the patch.
This is even worse in some std::deque implementations where thousands of allocations and dealloactions for each mouse move would grind the client to a halt (which is what actually prompted me to investigate the issue).
The best way to go about testing this would be running unpatched …

Improve mouse move event propagation

---

modules/corelib/ui/tooltip.lua

This fixes the bug I introduced in #1037. The tooltip position is now updated through the onMouseMove event in the root widget which always receives mouse updates.

Fix tooltip position updating

---

src/client/position.h
src/framework/util/color.h

GCC 9 adds a new diagnostic (-Wdeprecated-copy) that addresses the following:
>The generation of the implicitly-defined copy constructor is deprecated if T has a user-defined destructor or user-defined copy assignment operator. 
This results in dozens of warnings in all files that include the Color and Position classes as those classes supply user-defined copy assignment but no explicit copy constructor.

Add default copy constructors to Color and Position classes

---

src/framework/core/filestream.cpp
src/framework/core/resourcemanager.cpp

This replaces the deprecated PhysFS functions with their non-deprecated variant. The code should ***not*** break for older PhysFS versions as the functions existed in prior versions.
* `PHYSFS_read` => `PHYSFS_readBytes`
* `PHYSFS_write` => `PHYSFS_writeBytes`
* `PHYSFS_getLastError` => `PHYSFS_getErrorByCode(PHYSFS_getLastErrorCode())`
* `PHYSFS_addToSearchPath` => `PHYSFS_mount`
* `PHYSFS_removeFromSearchPath` => `PHYSFS_unmount`
* `PHYSFS_isDirectory` => `PHYSFS_stat` (+ stat struct flag check)
This however doesn't remove the deprecated PHYSFS_getUserDir for the following two reasons:
* It seems like the library doesn't like the order in which things are initialized in otc and PHYSFS_getPerfDir may return a null pointer in some cases (would require further investigation).
* It changes …

Fix use of deprecated PhysFS functions

---

src/framework/ui/uiwidgettext.cpp

The correct definition of offset is to displace the text no matter what the alignment is.

Correcting text offset

---

.travis.yml

This updates the Travis file to pull PhysFS 3 as mentioned in #1044 and #1045.

Update Travis build file to use physfs stable 3.0 branch

---

src/framework/net/connection.cpp
src/framework/net/connection.h

There seems to be an issue with static storage linkage in debug mode that may result in undefined references to these variables, this should address the issue. I also checked with [forgottenserver](https://github.com/otland/forgottenserver/blob/master/src/connection.h#L27-L28) to see how they had handled the breaking change in Boost a while ago and it seems to be done in the same way (likely for the same reason).

Fix an issue with Connection class linkage

---

src/framework/stdext/demangle.cpp

In #1044 I had introduced a subtle bug where the demangled symbol name buffer could end up without a null terminator if the length of the demangled symbol name was equal or greater than the buffer size, this fixes the issue.

Fix a possible missing null terminator in the demangle_name output buffer

---

modules/client_locales/locales.lua

fix language selection bug
steps to reproduce:
- go to c:/users/username/otclient and remove settings file
- launch otclient
- select english
- restart otclient
expected behaviour: no more startup prompts for language selection when selecting default language
observed behaviour: everytime client gets restarted and you click the default language, it doesn't get saved if it didn't exist in config file previously

fix initial language selection

---

src/client/tile.cpp

In https://github.com/edubart/otclient/issues/1040#issuecomment-581173589 we had a discussion if tile:draw() redrawing in case of lying corpse either is needed or not. We came to conclusion that there are way too many downsides of this resolution and therefore we opt against redrawing. Both performance-wise and gameplay-wise it is better without redrawing.

Getting rid of redraw on lying corpse

---

modules/game_skills/skills.lua

After applying 714c6b8fc01f9197288695621014ba193f809b7f (#1085), this should be changed too.
Terminal was spamming this warning even though it worked fine.

Fix comma_value result treated as an int

---

src/framework/core/resourcemanager.cpp

https://github.com/otland/otclient/pull/43
Before directoryExists method called resolvePath on input. Later change was introduced that changed that behavior silently breaking some things(most notably CandyBot ui). This PR fixes that.

resourcemanager:[bug fix] directoryExists method should resolvePath before checking

---

src/framework/platform/unixplatform.cpp

Hi. This patch fixes a crash on machines that don't have "model name" in cpuinfo and have empty lines in that file. When some lines were empty then there was no strs[1] so we had a out of bound read.
Please review @diath 
Cheers

[unixplatform] fix getCPUName crash

---

src/framework/util/point.h

There is no method named after getLength inside TPoint, and once this is a template implementation the error will only show up when trying to use distanceFrom method.

Updated call to getLength

---

src/client/tile.h

This patch returns vector by const ref instead of making copy. If the copy is needed the calling function can make it instead. In remaining two cases we are creating new vectors so we can't do that. New vectors should be returned by RVO so it shouldn't be a problem.

[tile] return vector by const ref instead of copy

---

.github/workflows/build-vcpkg.yml

vcpkg does not provide [version of lua](https://github.com/microsoft/vcpkg/blob/master/versions/l-/lua.json) that could be used to compile otclient.

Run windows workflow with luajit only

---

src/client/position.h
src/framework/const.h
src/framework/graphics/particleaffector.cpp

Use float literals to perform more calculation in float instead of performing implicit conversion to double and back to float.

use float literals

---

src/framework/core/logger.cpp
src/framework/core/logger.h

Some small improvements after that caught my attention. We don't need to make a copy because 'm_onLog' can't change anything. I think onLog is used when you bring up client console so lua can show you logs.

keep logs in deque and don't make unnecessary copy

---

src/framework/net/protocol.cpp
src/framework/net/protocol.h

Pushing the same code present in TFS. Tired of seeing this being sold in plain sight :stuck_out_tongue_closed_eyes: 
"This patch enables auto-vectorization for XTEA encryption and decryption, exploring vector (SSE, AVX) instructions to be auto-enabled by the compiler. Should render up to 16x faster encryption/decryption throughput on AVX2, 8x on AVX and 4x on SSE/Neon."
"Out with all that optimal block size width, let the compiler figure it out. Reduces the amount of code by half and increases performance by ~20%."
[Reasoning and detailed study](https://dev.to/rsa/making-an-algorithm-15x-faster-without-parallelism-38k5)

Optimize XTEA encryption

---

vc14/otclient.vcxproj

I would appreciate if someone else would test whether this fixes the vcpkg setup. It should work without any adjustments following the instruction at https://github.com/edubart/otclient/wiki/Compiling-on-Windows.
Related: #1073

Fix vcpkg compiling

---

src/client/animatedtext.cpp
src/client/map.cpp
src/client/outfit.cpp
src/client/position.h
src/client/uiprogressrect.cpp
src/framework/ui/uiwidget.cpp

Use float literals to perform more calculation in float instead of performing implicit conversion to double and back to float.
This fixes warnings with -Wdouble-promotion

Use float literals where applicable, fix -Wdouble-promotion
