edubart/otclient

- modules/game_console/console.lua
- modules/game_market/market.lua
- modules/game_market/marketoffer.lua
- modules/game_market/marketprotocol.lua
- modules/game_market/ui/myoffers/currentoffers.otui
My offers in market are now shown and can be canceled. What is missing:
You have to refresh offers after You go to "My offers" to get them. No item can be selected when refreshing (use reset).
> Market myoffers + NPC start block

- modules/gamelib/const.lua
- src/client/const.h
- src/client/game.cpp
- src/client/thingtype.cpp
- src/client/thingtype.h
This is necessary to disable the feature when necessary.
https://otland.net/threads/10-76-animation-bug.233461/
> Add a flag for idle animation game feature.

- modules/gamelib/const.lua
- src/client/const.h
- src/client/map.cpp
Remove tiles that we are not aware anymore by default.
> Add 'GameKeepUnawareTiles' feature.

- vc14/arch32.props
- vc14/arch64.props
- vc14/debug.props
- vc14/otclient.vcxproj
- vc14/register_otclient_boost_env.bat
- vc14/register_otclient_sdk_env.bat
- vc14/release.props
- vc14/settings.props
Update Visual Studio to work with PATH system variables in Windows
systems. Credits go to @Radseq for changing the project and to me for
update to Visual Studio 2015
Closes
#795
#746
#718
#724
#713
> Update Visual Studio Project

- src/client/thingtype.cpp
These changes we join the idle animations with the walking animations
> Bug idle animations of the creatures solved

- modules/client_entergame/characterlist.lua
When trying to logout in battle the player would not logout and tryLogin
would be called, so the next time you tryed to login it will still be
trying to login
> Fix Login problem and use removeEvent

- src/framework/luafunctions.cpp
Fix iptostring bug that blocks access to half of OTSes
> Fix iptostring in LUA

- modules/client_background/background.lua
Add function getBackground in client_background module.
Function getBackground return background value, who contain background UI (login screen).
Function will enable adding things to login screen from external modules, without modifying client_background module.
modules.client_background.getBackground()
> Add function getBackground

- modules/game_interface/gameinterface.lua
Extending the possibilities of "UICreatureButton" widget.
**Feature from normal client:**
Adding possibility sending trade request in battle list (game_battle module) and other modules who use widget "UICreatureButton".
> Sending trade request using "UICreatureButton"

- src/framework/platform/unixcrashhandler.cpp
> Fix a missing include in unix crash handler

- src/framework/stdext/shared_object.h
> fixed clang 9 compile errors in shared_object_ptr

- src/client/game.cpp
- src/client/game.h
- src/client/protocolgame.h
- src/client/protocolgamesend.cpp
Fixes TFS's training dialog which uses ID 0xFFFFFFFF.
> Fix data type for Modal Dialog ID

- src/client/game.cpp
- src/client/game.h
This will fix missing t in outfit parameter
> Fix wrong parameter name in source

- modules/client_entergame/characterlist.lua
- modules/gamelib/const.lua
- modules/gamelib/protocollogin.lua
> Fix parsing the premium status in newer login protocol versions

- .gitignore
- src/framework/net/connection.h
- src/framework/sound/declarations.h
- vc14/otclient.vcxproj
* Compilation fixes (see https://github.com/otland/forgottenserver/commit/7193a670c6b5b7cff472e1946e5b1e7ca7e1051b#diff-70002a4cfb8e3fd5d00493262492a5daR27)
* OpenAL path compatible with vcpkg
* Optimizations in MSVS
> Compilation & linking fixes

- modules/corelib/ui/uiscrollbar.lua
This adds extra convenience key modifiers to the scrollbar controls for moving to the beginning/end and by -10/+10.
> Improve scrollbar navigation

- src/client/creature.cpp
nextT should cast double as it's a second degree equation and results in a double type. -> Bhaskara.
> Function updateJump() fix

- modules/corelib/ui/uicombobox.lua
Fixed getOption who always return nil.
Rename getOption to isOption.
> Fixed getOption and rename to isOption

- Dockerfile
- README.md
- build.sh
- run.sh
Put [documentations](https://github.com/edubart/otclient/wiki/Compiling-on-Linux) about compile and run on linux into a automated Dockerfile and scripts to build and run on container.
> Docker support

- Dockerfile
As I mentioned in #1053 i found a fix to the issue, just updating the physfs from 2.0 to 3.0.
> Update dockerfile to use physfs stable 3.0

- modules/game_battle/battle.lua
- modules/game_console/console.lua
- modules/game_containers/containers.lua
- modules/game_interface/widgets/uigamemap.lua
- modules/game_interface/widgets/uiitem.lua
Fixes to bugs that I found while using the client.
> Fixes for hard to find bugs

- modules/game_modaldialog/modaldialog.lua
selecting first modalwindow choice by default like in cip client
> focus first choice in modalWindow by default (QoL)

- modules/game_modaldialog/modaldialog.lua
QoL change, that's how it works in the official client
> allow using up/down arrows in modalWindow

- src/framework/CMakeLists.txt
- src/framework/luafunctions.cpp
- src/framework/util/crypt.cpp
- src/framework/util/crypt.h
This is a new code based on posted PRs. However, it uses automatic fallback to GMP if OpenSSL is not found.
I did not test it myself. Also, the implemention is open for discussion.
> Support for OpenSSL with a fallback to GMP

- modules/game_skills/skills.lua
- modules/gamelib/util.lua
Using commas separating for big number in skills window to make the numbers more readable.
Updated latest file version.
> Big number separating

- .github/workflows/build-vcpkg.yml
- .gitignore
> Add Github workflows

- src/framework/platform/win32window.cpp
Client's window now returns into proper monitor instead of always first monitor
> Fixed window returning from fullscreen

- src/client/map.cpp
- src/framework/core/eventdispatcher.cpp
- src/framework/core/eventdispatcher.h
- src/framework/stdext/time.h
as requested in https://github.com/edubart/otclient/pull/1108
> use deque for queues

- src/client/luafunctions.cpp
Add Missile:setPath(fromPos, toPos) method to Lua interface.
> Add Missile:setPath to Lua interface

- modules/client/client.lua
- modules/client_options/options.lua
This patch fix lua crash if otclient is compiled without sound support
> fix lua if compiled without sound

- src/client/localplayer.cpp
- src/client/localplayer.h
found due to uninitialized variable warning on gcc11
> [localplayer] fix passing oldMaxMana to lua in setMana function

- modules/game_skills/skills.lua
Changed only values that I could test myself.
> [skills] 2400min is still premium stamina

- src/framework/platform/unixplatform.cpp
> Fix opening urls on macOS

- Dockerfile
> Update physfs repo in Dockerfile

- vc14/otclient.vcxproj
> Correctly include vcpkg luajit in visual studio

- .github/workflows/build-vcpkg.yml
Resolving deprecations:
* Updating node (12->16)
* save-state & save-output methods to env file
> Update workflow actions
